version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo "Package & Dependicies are getting installed"
      - sudo apt-get -y update
      - sudo apt install nodejs -y
      - sudo apt install npm -y
      - sudo npm install pm2@latest -g
      - echo "Packages have been installed"
      - echon "Storing Build Artifact to the Location"
artifacts:
  type: zip
  paths:
    - '*'
